[package]
name = "attraction"
version = "0.1.0"
authors = ["d_yama <d_yama@hololab.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.1"
metered = "0.7.0"